{
 "title": "AWS -Brasil Prev",
 "description": "Visualize estimated AWS charges per AWS resource (EC2, S3, ...)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Compliance Brasil Prev", "type": "text", "gridPos": { "h": 1, "w": 22, "x": 1, "y": 0 }, "options": { "content": "\n\n\n" } },
  {
   "title": "#############################################################################################################################################################################################################",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "content": "\n\n\n" }
  },
  {
   "title": "Total Instances ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Running Total Instances" },
     "itemTag": { "filter": "Application: EC2" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EC2 Sem  Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Instancias Sem TAG" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SG Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "SG Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SG sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "SG no Tags Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total ELB",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ELB" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "ELB Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ELB Sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ELB" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "ELB no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AMI Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "EC2 AMI Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AMI Sem Tag",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "EC2 AMI IDs" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EIP Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "EIP Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EIP sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "EIP no Tags Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IAM Roles Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "IAM" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "IAM Role Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IAM Roles sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "IAM" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "IAM Role no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IDS EC2 sem Tags",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "EC2 IDS" },
     "itemTag": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SG no Tags",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "SG IDS no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ELB Sem Tags",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "application": { "filter": "ELB" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "ELB no Tags Names" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AMI Sem Tag",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "EC2 AMI IDs" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EPI Sem Tag",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "EIP IDS no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IAM Roles Sem Tag",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "application": { "filter": "IAM" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "IAM Role Names no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "#############################################################################################################################################################################################################",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "options": { "content": "\n\n\n" }
  },
  {
   "title": "Total Buckets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Buckets S3" },
     "itemTag": { "filter": "Application: S3" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "S3 sem Tag",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Buckets S3 Sem Tag" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "S3 unencrypted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Buckets S3 Sem Criptografia" },
     "itemTag": { "filter": "Application: S3" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total RDS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "RDS Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RDS Sem TAG",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "TAG" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "RDS Sem TAG" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VPC Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "VPC Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VPC sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "VPC no Tags Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ECS Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ECS" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "ECS Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ECS sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ECS" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "ECS no Tags Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Lambdas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Lambda" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "lambda-total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lambda sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Lambda" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Lambda no Tags Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "S3 Names",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "S3 Names" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "S3 unencrypted",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 16 },
   "targets": [
    {
     "application": { "filter": "S3" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "S3 unencrypted IDS" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IDS RDS sem Tags",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 16 },
   "targets": [
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "RDS IDS" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VPC Sem Tag",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 16 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "VPC IDS no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ECS Sem Tag",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 16 },
   "targets": [
    {
     "application": { "filter": "ECS" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "ECS IDS no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lambdas Sem Tags",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 16 },
   "targets": [
    {
     "application": { "filter": "Lambda" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Lambda sem Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "#############################################################################################################################################################################################################",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "options": { "content": "\n\n\n" }
  },
  {
   "title": "Snap Priv Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Snapshot Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Snap Priv sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Snapshot no Tags Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Snap Public Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Snapshot Public Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Snap DB Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Snapshot DBs Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Snap DB Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Snapshot DBs no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CloudFront Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CloudFront" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Cloudfront Total" },
     "itemTag": { "filter": "Application: S3" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CloudFront sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CloudFront" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Cloudfront no Tags" },
     "itemTag": { "filter": "Application: S3" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Beanstalk Total ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Elastic Beanstalk" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Elastic Beanstalk Total" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Beanstalk sem Tags",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Elastic Beanstalk" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Elastic Beanstalk no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Snap private sem Tags",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 25 },
   "targets": [
    {
     "application": { "filter": "EC2" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Snapshot IDs no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Snap DB sem Tags",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 25 },
   "targets": [
    {
     "application": { "filter": "RDS" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Snapshot DBs IDs no Tags" },
     "itemTag": { "filter": "Application: TAG" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CloudFront sem Tags",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 25 },
   "targets": [
    {
     "application": { "filter": "CloudFront" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": { "filter": "Cloudfront Names no Tags" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IDS Beanstalk sem Tags",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 25 },
   "targets": [
    {
     "application": { "filter": "Elastic Beanstalk" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "AWS" },
     "item": {
      "filter": "Elastic Beanstalk Names no Tags"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}