- hosts: web
  become: true
  gather_facts: true
  vars_files:
    - ../vars/urls.yml
  pre_tasks:
    - name: Set repo if Alpine
      ansible.builtin.set_fact:
        version: "=1.21.6-r1"
      when: ansible_facts['os_family'] == "Alpine"
    - name: Set repo if Debian
      ansible.builtin.set_fact:
        version: "=1.21.6-1~{{ ansible_facts['distribution_release'] }}"
      when: ansible_facts['os_family'] == "Debian"
    - name: Set repo if Red Hat
      ansible.builtin.set_fact:
        version: "-1.21.6-1.{{ (ansible_facts['distribution'] == 'Amazon') | ternary('amzn2', ('el' + ansible_facts['distribution_major_version'] | string)) }}.ngx"
      when: ansible_facts['os_family'] == "RedHat"
  tasks:
    # load dynamic vars
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../vars/web.yml

    - name: Include nginxinc.nginx
      ansible.builtin.include_role:
        name: nginxinc.nginx
      vars:
        nginx_version: "{{ version }}"

    - name: Include nginxinc.nginx_config
      ansible.builtin.include_role:
        name: nginxinc.nginx_config
